// gameData.ts
import { Game, CollegeTeam } from './types';

// College teams we played against
export const collegeTeams: CollegeTeam[] = [
  { name: "CCL UWATERLOO TEAM B W25(Playoff: Finals)", id: "uwaterloo-b" },
  { name: "University of Washington-B(Regular)", id: "washington-b" },
  { name: "VIT I 2025 (INT CCL)(Playoff: Quarterfinals)", id: "vit-i" },
  { name: "University of Texas at Austin - D(Regular)", id: "texas-austin-d" },
  { name: "UNIZAMBEZEA A(Regular)", id: "unizambezea-a" },
  {name: "University of Washington-B(Playoff: Semi Finals)", id: "univ-wash_playoff" }
];

// All games data
export const allGames: Game[] = [
  // Kunal vs UWATERLOO TEAM B
  { 
    id: 1, 
    opponent: "Chess_nut_Tree", 
    result: "win", 
    date: "2025-04-05",
    chessComId: "13252190",
    round: "Round 1",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: king_kunal",
    collegeTeam: "uwaterloo-b",
    playerName: "Kunal Shrivastav"
  },
  { 
    id: 2, 
    opponent: "Chyessirree", 
    result: "loss", 
    date: "2025-04-05",
    chessComId: "13252192",
    round: "Round 2",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: king_kunal",
    collegeTeam: "uwaterloo-b",
    playerName: "Kunal Shrivastav"
  },
  { 
    id: 3, 
    opponent: "lasdw", 
    result: "win", 
    date: "2025-04-05",
    chessComId: "13252196",
    round: "Round 3",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: king_kunal",
    collegeTeam: "uwaterloo-b",
    playerName: "Kunal Shrivastav"
  },
  { 
    id: 4, 
    opponent: "ComingForCM", 
    result: "win", 
    date: "2025-04-05",
    chessComId: "13252200",
    round: "Round 4",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: king_kunal",
    collegeTeam: "uwaterloo-b",
    playerName: "Kunal Shrivastav"
  },
  { 
    id: 5, 
    opponent: "ComingForCM", 
    result: "win", 
    date: "2025-04-05",
    chessComId: "13252204",
    round: "Round 5",
    timeControl: "3+2",
    playedAs: "black",
    notes: "Player username: king_kunal",
    collegeTeam: "uwaterloo-b",
    playerName: "Kunal Shrivastav"
  },
  { 
    id: 6, 
    opponent: "ComingForCM", 
    result: "win", 
    date: "2025-04-05",
    chessComId: "13252208",
    round: "Round 6 (Final)",
    timeControl: "1+2",
    playedAs: "white",
    notes: "Player username: king_kunal",
    collegeTeam: "uwaterloo-b",
    playerName: "Kunal Shrivastav"
  },
  
  // Kunal vs University of Texas at Austin - D
  {
    id: 7,
    opponent: "DieRoten4002",
    result: "win",
    date: "2025-03-01",
    chessComId: "13252216",
    round: "Round 1",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: king_kunal",
    collegeTeam: "texas-austin-d",
    playerName: "Kunal Shrivastav"
  },
  {
    id: 8,
    opponent: "ChessCraze012",
    result: "win",
    date: "2025-03-01",
    chessComId: "13252222",
    round: "Round 2",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: king_kunal",
    collegeTeam: "texas-austin-d",
    playerName: "Kunal Shrivastav"
  },
  {
    id: 9,
    opponent: "KnifeEffSix",
    result: "win",
    date: "2025-03-01",
    chessComId: "13252226",
    round: "Round 3",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: king_kunal",
    collegeTeam: "texas-austin-d",
    playerName: "Kunal Shrivastav"
  },
  {
    id: 10,
    opponent: "DrqgonRage",
    result: "win",
    date: "2025-03-01",
    chessComId: "13252232",
    round: "Round 4",
    timeControl: "5+2",
    playedAs: "black",
    collegeTeam: "texas-austin-d",
    playerName: "Kunal Shrivastav"
  },
  
  // Vedh vs UWATERLOO TEAM B
  {
    id: 11,
    opponent: "lasdw",
    result: "win",
    date: "2025-04-05",
    chessComId: "13252234",
    round: "Round 1",
    timeControl: "5+2",
    playedAs: "white",
    collegeTeam: "uwaterloo-b",
    playerName: "Vedh Vasu"
  },
  {
    id: 12,
    opponent: "ComingForCM",
    result: "loss",
    date: "2025-04-05",
    chessComId: "13252236",
    round: "Round 2",
    timeControl: "5+2",
    playedAs: "black",
    collegeTeam: "uwaterloo-b",
    playerName: "Vedh Vasu"
  },
  {
    id: 13,
    opponent: "Chess_nut_Tree",
    result: "win",
    date: "2025-04-05",
    chessComId: "13252238",
    round: "Round 3",
    timeControl: "5+2",
    playedAs: "white",
    collegeTeam: "uwaterloo-b",
    playerName: "Vedh Vasu"
  },
  {
    id: 14,
    opponent: "Chyessirree",
    result: "win",
    date: "2025-04-05",
    chessComId: "13252246",
    round: "Round 4",
    timeControl: "5+2",
    playedAs: "black",
    collegeTeam: "uwaterloo-b",
    playerName: "Vedh Vasu"
  },
  {
    id: 15,
    opponent: "Chyessirree",
    result: "loss",
    date: "2025-04-05",
    chessComId: "13252252",
    round: "Round 5",
    timeControl: "3+2",
    playedAs: "white",
    collegeTeam: "uwaterloo-b",
    playerName: "Vedh Vasu"
  },
  {
    id: 16,
    opponent: "Chyessirree",
    result: "win",
    date: "2025-04-05",
    chessComId: "13252256",
    round: "Round 6 (Final)",
    timeControl: "1+2",
    playedAs: "black",
    collegeTeam: "uwaterloo-b",
    playerName: "Vedh Vasu"
  },
  
  // Vedh vs University of Texas at Austin - D
  {
    id: 17,
    opponent: "KnifeEffSix",
    result: "loss",
    date: "2025-03-01",
    chessComId: "13252620",
    round: "Round 1",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: coolguy3949",
    collegeTeam: "texas-austin-d",
    playerName: "Vedh Vasu"
  },
  {
    id: 18,
    opponent: "DrqgonRage",
    result: "loss",
    date: "2025-03-01",
    chessComId: "13252622",
    round: "Round 2",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: coolguy3949",
    collegeTeam: "texas-austin-d",
    playerName: "Vedh Vasu"
  },
  {
    id: 19,
    opponent: "DieRoten4002",
    result: "loss",
    date: "2025-03-01",
    chessComId: "13252626",
    round: "Round 3",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: coolguy3949",
    collegeTeam: "texas-austin-d",
    playerName: "Vedh Vasu"
  },
  {
    id: 20,
    opponent: "ChessCraze012",
    result: "win",
    date: "2025-03-01",
    chessComId: "13252628",
    round: "Round 4",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: coolguy3949",
    collegeTeam: "texas-austin-d",
    playerName: "Vedh Vasu"
  },
  
  // Falak vs UWATERLOO TEAM B
  {
    id: 21,
    opponent: "ComingForCM",
    result: "loss",
    date: "2025-04-05",
    chessComId: "13252258",
    round: "Round 1",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: skizzers13",
    collegeTeam: "uwaterloo-b",
    playerName: "Falak Tulsi"
  },
  {
    id: 22,
    opponent: "lasdw",
    result: "loss",
    date: "2025-04-05",
    chessComId: "13252262",
    round: "Round 2",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: skizzers13",
    collegeTeam: "uwaterloo-b",
    playerName: "Falak Tulsi"
  },
  {
    id: 23,
    opponent: "N/A",
    result: "loss",
    date: "2025-04-05",
    round: "Round 3",
    timeControl: "N/A",
    notes: "Player did not participate",
    collegeTeam: "uwaterloo-b",
    playerName: "Falak Tulsi"
  },
  {
    id: 24,
    opponent: "N/A",
    result: "loss",
    date: "2025-04-05",
    round: "Round 4",
    timeControl: "N/A",
    notes: "Player did not participate",
    collegeTeam: "uwaterloo-b",
    playerName: "Falak Tulsi"
  },
  {
    id: 25,
    opponent: "N/A",
    result: "loss",
    date: "2025-04-05",
    round: "Round 5",
    timeControl: "N/A",
    notes: "Player did not participate",
    collegeTeam: "uwaterloo-b",
    playerName: "Falak Tulsi"
  },
  {
    id: 26,
    opponent: "N/A",
    result: "loss",
    date: "2025-04-05",
    round: "Round 6",
    timeControl: "N/A",
    notes: "Player did not participate",
    collegeTeam: "uwaterloo-b",
    playerName: "Falak Tulsi"
  },
  
  // Maanas vs UWATERLOO TEAM B
  {
    id: 27,
    opponent: "Chyessirree",
    result: "win",
    date: "2025-04-05",
    chessComId: "13252270",
    round: "Round 1",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: SuperMaanas",
    collegeTeam: "uwaterloo-b",
    playerName: "Maanas Kollegal"
  },
  {
    id: 28,
    opponent: "Chess_nut_Tree",
    result: "win",
    date: "2025-04-05",
    chessComId: "13252272",
    round: "Round 2",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: SuperMaanas",
    collegeTeam: "uwaterloo-b",
    playerName: "Maanas Kollegal"
  },
  {
    id: 29,
    opponent: "ComingForCM",
    result: "loss",
    date: "2025-04-05",
    chessComId: "13252274",
    round: "Round 3",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: SuperMaanas",
    collegeTeam: "uwaterloo-b",
    playerName: "Maanas Kollegal"
  },
  {
    id: 30,
    opponent: "lasdw",
    result: "loss",
    date: "2025-04-05",
    chessComId: "13252276",
    round: "Round 4",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: SuperMaanas",
    collegeTeam: "uwaterloo-b",
    playerName: "Maanas Kollegal"
  },
  {
    id: 31,
    opponent: "lasdw",
    result: "win",
    date: "2025-04-05",
    chessComId: "13252278",
    round: "Round 5",
    timeControl: "3+2",
    playedAs: "black",
    notes: "Player username: SuperMaanas",
    collegeTeam: "uwaterloo-b",
    playerName: "Maanas Kollegal"
  },
  {
    id: 32,
    opponent: "lasdw",
    result: "win",
    date: "2025-04-05",
    chessComId: "13252282",
    round: "Round 6 (Final)",
    timeControl: "1+2",
    playedAs: "white",
    notes: "Player username: SuperMaanas",
    collegeTeam: "uwaterloo-b",
    playerName: "Maanas Kollegal"
  },
  // Maanas vs University of Texas at Austin - D
  {
    id: 33,
    opponent: "ChessCraze012",
    result: "draw",
    date: "2025-03-01",
    chessComId: "13252286",
    round: "Round 1",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: SuperMaanas",
    collegeTeam: "texas-austin-d",
    playerName: "Maanas Kollegal"
  },
  {
    id: 34,
    opponent: "DieRoten4002",
    result: "win",
    date: "2025-03-01",
    chessComId: "13252440",
    round: "Round 2",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: SuperMaanas",
    collegeTeam: "texas-austin-d",
    playerName: "Maanas Kollegal"
  },
  {
    id: 35,
    opponent: "DrqgonRage",
    result: "win",
    date: "2025-03-01",
    chessComId: "13252442",
    round: "Round 3",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: SuperMaanas",
    collegeTeam: "texas-austin-d",
    playerName: "Maanas Kollegal"
  },
  {
    id: 36,
    opponent: "KnifeEffSix",
    result: "draw",
    date: "2025-03-01",
    chessComId: "13252444",
    round: "Round 4",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: SuperMaanas",
    collegeTeam: "texas-austin-d",
    playerName: "Maanas Kollegal"
  },
  // Falak vs University of Texas at Austin - D
  {
    id: 37,
    opponent: "DrqgonRage",
    result: "win",
    date: "2025-03-01",
    chessComId: "13252604",
    round: "Round 1",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: skizzers13",
    collegeTeam: "texas-austin-d",
    playerName: "Falak Tulsi"
  },
  {
    id: 38,
    opponent: "KnifeEffSix",
    result: "loss",
    date: "2025-03-01",
    chessComId: "13252610",
    round: "Round 2",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: skizzers13",
    collegeTeam: "texas-austin-d",
    playerName: "Falak Tulsi"
  },
  {
    id: 39,
    opponent: "ChessCraze012",
    result: "loss",
    date: "2025-03-01",
    chessComId: "13252614",
    round: "Round 3",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: skizzers13",
    collegeTeam: "texas-austin-d",
    playerName: "Falak Tulsi"
  },
  {
    id: 40,
    opponent: "DieRoten4002",
    result: "loss",
    date: "2025-03-01",
    chessComId: "13252616",
    round: "Round 4",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: skizzers13",
    collegeTeam: "texas-austin-d",
    playerName: "Falak Tulsi"
  },
  // Kunal vs UNIZAMBEZEA A
  {
    id: 41,
    opponent: "Elio_3",
    result: "win",
    date: "2025-02-08",
    chessComId: "13252630",
    round: "Round 1",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: king_kunal",
    collegeTeam: "unizambezea-a",
    playerName: "Kunal Shrivastav"
  },
  {
    id: 42,
    opponent: "Chissale19QI",
    result: "win",
    date: "2025-02-08",
    chessComId: "13252634",
    round: "Round 2",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: king_kunal",
    collegeTeam: "unizambezea-a",
    playerName: "Kunal Shrivastav"
  },
  {
    id: 43,
    opponent: "agm2002",
    result: "win",
    date: "2025-02-08",
    chessComId: "13252636",
    round: "Round 3",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: king_kunal",
    collegeTeam: "unizambezea-a",
    playerName: "Kunal Shrivastav"
  },
  {
    id: 44,
    opponent: "jojoabdul",
    result: "win",
    date: "2025-02-08",
    chessComId: "13252638",
    round: "Round 4",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: king_kunal",
    collegeTeam: "unizambezea-a",
    playerName: "Kunal Shrivastav"
  },
  // Maanas vs UNIZAMBEZEA A
  {
    id: 45,
    opponent: "Chissale19QI",
    result: "win",
    date: "2025-02-08",
    chessComId: "13144760",
    round: "Round 1",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: SuperMaanas",
    collegeTeam: "unizambezea-a",
    playerName: "Maanas Kollegal"
  },
  {
    id: 46,
    opponent: "Elio_3",
    result: "win",
    date: "2025-02-08",
    chessComId: "13252648",
    round: "Round 2",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: SuperMaanas",
    collegeTeam: "unizambezea-a",
    playerName: "Maanas Kollegal"
  },
  {
    id: 47,
    opponent: "jojoabdul",
    result: "loss",
    date: "2025-02-08",
    chessComId: "13252654",
    round: "Round 3",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: SuperMaanas",
    collegeTeam: "unizambezea-a",
    playerName: "Maanas Kollegal"
  },
  {
    id: 48,
    opponent: "agm2002",
    result: "loss",
    date: "2025-02-08",
    chessComId: "13252656",
    round: "Round 4",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: SuperMaanas",
    collegeTeam: "unizambezea-a",
    playerName: "Maanas Kollegal"
  },
  //vedh uniz
  {
    id: 49,
    opponent: "agm2002",
    result: "loss",
    date: "2025-02-08",
    chessComId: "13252660",
    round: "Round 1",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: coolguy3949",
    collegeTeam: "unizambezea-a",
    playerName: "Vedh Vasu"
  },
  {
    id: 50,
    opponent: "jojoabdul",
    result: "loss",
    date: "2025-02-08",
    chessComId: "13252662",
    round: "Round 2",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: coolguy3949",
    collegeTeam: "unizambezea-a",
    playerName: "Vedh Vasu"
  },
  {
    id: 51,
    opponent: "Elio_3",
    result: "win",
    date: "2025-02-08",
    chessComId: "13252920",
    round: "Round 3",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: coolguy3949",
    collegeTeam: "unizambezea-a",
    playerName: "Vedh Vasu"
  },
  {
    id: 52,
    opponent: "Chissale19QI",
    result: "draw",
    date: "2025-02-08",
    chessComId: "13252922",
    round: "Round 4",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: coolguy3949",
    collegeTeam: "unizambezea-a",
    playerName: "Vedh Vasu"
  },
  //falak unizambeezea
  {
    id: 53,
    opponent: "jojoabdul",
    result: "loss",
    date: "2025-02-08",
    chessComId: "13252934",
    round: "Round 1",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: skizzers13",
    collegeTeam: "unizambezea-a",
    playerName: "Falak Tulsi"
  },
  {
    id: 54,
    opponent: "agm2002",
    result: "win",
    date: "2025-02-08",
    chessComId: "13252942",
    round: "Round 2",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: skizzers13",
    collegeTeam: "unizambezea-a",
    playerName: "Falak Tulsi"
  },
  {
    id: 55,
    opponent: "Chissale19QI",
    result: "loss",
    date: "2025-02-08",
    chessComId: "13252944",
    round: "Round 3",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: skizzers13",
    collegeTeam: "unizambezea-a",
    playerName: "Falak Tulsi"
  },
  {
    id: 56,
    opponent: "Elio_3",
    result: "win",
    date: "2025-02-08",
    chessComId: "13252946",
    round: "Round 4",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: skizzers13",
    collegeTeam: "unizambezea-a",
    playerName: "Falak Tulsi"
  },
  //kunal games against univ-washington 03/08/
  {
    id: 57,
    opponent: "sdpandit",
    result: "win",
    date: "2025-03-08",
    chessComId: "13252958",
    round: "Round 1",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: king_kunal",
    collegeTeam: "washington-b",
    playerName: "Kunal Shrivastav"
  },
  {
    id: 58,
    opponent: "SirPoetVic",
    result: "win",
    date: "2025-03-08",
    chessComId: "13252960",
    round: "Round 2",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: king_kunal",
    collegeTeam: "washington-b",
    playerName: "Kunal Shrivastav"
  },
  {
    id: 59,
    opponent: "LionBlade45",
    result: "win",
    date: "2025-03-08",
    chessComId: "13252968",
    round: "Round 3",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: king_kunal",
    collegeTeam: "washington-b",
    playerName: "Kunal Shrivastav"
  },
  {
    id: 60,
    opponent: "jkmckenzzz",
    result: "win",
    date: "2025-03-08",
    chessComId: "13252976",
    round: "Round 4",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: king_kunal",
    collegeTeam: "washington-b",
    playerName: "Kunal Shrivastav"
  }, 
  {
    id: 61,
    opponent: "jkmckenzzz",
    result: "win",
    date: "2025-03-08",
    chessComId: "13252978",
    round: "Round 5",
    timeControl: "3+2",
    playedAs: "black",
    notes: "Player username: king_kunal",
    collegeTeam: "washington-b",
    playerName: "Kunal Shrivastav"
  }, 
  {
    id: 62,
    opponent: "jkmckenzzz",
    result: "win",
    date: "2025-03-08",
    chessComId: "13252980",
    round: "Round 6",
    timeControl: "1+2",
    playedAs: "white",
    notes: "Player username: king_kunal",
    collegeTeam: "washington-b",
    playerName: "Kunal Shrivastav"
  }, 
  {
    id: 63,
    opponent: "jkmckenzzz",
    result: "win",
    date: "2025-03-08",
    chessComId: "13252984",
    round: "Round 7",
    timeControl: "1+2",
    playedAs: "black",
    notes: "Player username: king_kunal",
    collegeTeam: "washington-b",
    playerName: "Kunal Shrivastav"
  }, 
  {
    id: 64,
    opponent: "jkmckenzzz",
    result: "win",
    date: "2025-03-08",
    chessComId: "13252986",
    round: "Round 8",
    timeControl: "1+2",
    playedAs: "white",
    notes: "Player username: king_kunal",
    collegeTeam: "washington-b",
    playerName: "Kunal Shrivastav"
  }, 
  {
    id: 65,
    opponent: "jkmckenzzz",
    result: "win",
    date: "2025-03-08",
    chessComId: "13252988",
    round: "Round 9",
    timeControl: "1+2",
    playedAs: "black",
    notes: "Player username: king_kunal",
    collegeTeam: "washington-b",
    playerName: "Kunal Shrivastav"
  }, 
  {
    id: 66,
    opponent: "jkmckenzzz",
    result: "win",
    date: "2025-03-08",
    chessComId: "13252992",
    round: "Round 10",
    timeControl: "1+2",
    playedAs: "white",
    notes: "Player username: king_kunal",
    collegeTeam: "washington-b",
    playerName: "Kunal Shrivastav"
  }, 

  //maanas games against Univ. Washington
  {
    id: 67,
    opponent: "SirPoetVic",
    result: "draw",
    date: "2025-03-08",
    chessComId: "13252998",
    round: "Round 1",
    timeControl: "5+2",
    playedAs: "black",
    collegeTeam: "washington-b",
    playerName: "Maanas Kollegal"
  },
  {
    id: 68,
    opponent: "sdpandit",
    result: "win",
    date: "2025-03-08",
    chessComId: "13253000",
    round: "Round 2",
    timeControl: "5+2",
    playedAs: "white",
    collegeTeam: "washington-b",
    playerName: "Maanas Kollegal"
  },
  {
    id: 69,
    opponent: "jkmckenzzz",
    result: "win",
    date: "2025-03-08",
    chessComId: "13253002",
    round: "Round 3",
    timeControl: "5+2",
    playedAs: "black",
    collegeTeam: "washington-b",
    playerName: "Maanas Kollegal"
  },
  {
    id: 70,
    opponent: "LionBlade45",
    result: "win",
    date: "2025-03-08",
    chessComId: "13145692",
    round: "Round 4",
    timeControl: "5+2",
    playedAs: "white",
    collegeTeam: "washington-b",
    playerName: "Maanas Kollegal"
  }, 
  {
    id: 71,
    opponent: "LionBlade45",
    result: "win",
    date: "2025-03-08",
    chessComId: "13145696",
    round: "Round 5",
    timeControl: "3+2",
    playedAs: "white",
    collegeTeam: "washington-b",
    playerName: "Maanas Kollegal"
  }, 
  {
    id: 72,
    opponent: "LionBlade45",
    result: "win",
    date: "2025-03-08",
    chessComId: "13145702",
    round: "Round 6",
    timeControl: "1+2",
    playedAs: "black",
    collegeTeam: "washington-b",
    playerName: "Maanas Kollegal"
  }, 
  {
    id: 73,
    opponent: "LionBlade45",
    result: "win",
    date: "2025-03-08",
    chessComId: "13253004",
    round: "Round 7",
    timeControl: "1+2",
    playedAs: "white",
    collegeTeam: "washington-b",
    playerName: "Maanas Kollegal"
  }, 
  {
    id: 74,
    opponent: "LionBlade45",
    result: "win",
    date: "2025-03-08",
    chessComId: "13253006",
    round: "Round 8",
    timeControl: "1+2",
    playedAs: "black",
    collegeTeam: "washington-b",
    playerName: "Maanas Kollegal"
  }, 
  {
    id: 75,
    opponent: "LionBlade45",
    result: "loss",
    date: "2025-03-08",
    chessComId: "13253010",
    round: "Round 9",
    timeControl: "1+2",
    playedAs: "white",
    collegeTeam: "washington-b",
    playerName: "Maanas Kollegal"
  }, 
  {
    id: 76,
    opponent: "LionBlade45",
    result: "win",
    date: "2025-03-08",
    chessComId: "13253012",
    round: "Round 10",
    timeControl: "1+2",
    playedAs: "black",
    collegeTeam: "washington-b",
    playerName: "Maanas Kollegal"
  },

  //vedh vasu's games against Univ-Washington 03/08
{
  id: 77,
  opponent: "LionBlade45",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13253060",
  round: "Round 1",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: coolguy3949",
  collegeTeam: "washington-b",
  playerName: "Vedh Vasu"
},
{
  id: 78,
  opponent: "jkmckenzzz",
  result: "draw",
  date: "2025-03-08",
  chessComId: "13145742",
  round: "Round 2",
  timeControl: "5+2",
  playedAs: "black",
  notes: "Player username: coolguy3949",
  collegeTeam: "washington-b",
  playerName: "Vedh Vasu"
},
{
  id: 79,
  opponent: "sdpandit",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13145744",
  round: "Round 3",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: coolguy3949",
  collegeTeam: "washington-b",
  playerName: "Vedh Vasu"
},
{
  id: 80,
  opponent: "SirPoetVic",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13253062",
  round: "Round 4",
  timeControl: "5+2",
  playedAs: "black",
  notes: "Player username: coolguy3949",
  collegeTeam: "washington-b",
  playerName: "Vedh Vasu"
},
{
  id: 81,
  opponent: "SirPoetVic",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13253064",
  round: "Round 5",
  timeControl: "3+2",
  playedAs: "white",
  notes: "Player username: coolguy3949",
  collegeTeam: "washington-b",
  playerName: "Vedh Vasu"
},
{
  id: 82,
  opponent: "SirPoetVic",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13145756",
  round: "Round 6",
  timeControl: "1+2",
  playedAs: "black",
  notes: "Player username: coolguy3949",
  collegeTeam: "washington-b",
  playerName: "Vedh Vasu"
},
{
  id: 83,
  opponent: "SirPoetVic",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13253070",
  round: "Round 7",
  timeControl: "1+2",
  playedAs: "white",
  notes: "Player username: coolguy3949",
  collegeTeam: "washington-b",
  playerName: "Vedh Vasu"
},
{
  id: 84,
  opponent: "SirPoetVic",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13145776",
  round: "Round 8",
  timeControl: "1+2",
  playedAs: "black",
  notes: "Player username: coolguy3949",
  collegeTeam: "washington-b",
  playerName: "Vedh Vasu"
},
{
  id: 85,
  opponent: "SirPoetVic",
  result: "win",
  date: "2025-03-08",
  chessComId: "13253072",
  round: "Round 9",
  timeControl: "1+2",
  playedAs: "white",
  notes: "Player username: coolguy3949",
  collegeTeam: "washington-b",
  playerName: "Vedh Vasu"
},
{
  id: 86,
  opponent: "SirPoetVic",
  result: "win",
  date: "2025-03-08",
  chessComId: "13253076",
  round: "Round 10",
  timeControl: "1+2",
  playedAs: "black",
  notes: "Player username: coolguy3949",
  collegeTeam: "washington-b",
  playerName: "Vedh Vasu"
},

//Falak Tulsi's games against Univ-Washington 03/08
{
  id: 87,
  opponent: "jkmckenzzz",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13253112",
  round: "Round 1",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: skizzers13",
  collegeTeam: "washington-b",
  playerName: "Falak Tulsi"
},
{
  id: 88,
  opponent: "LionBlade45",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13253114",
  round: "Round 2",
  timeControl: "5+2",
  playedAs: "black",
  notes: "Player username: skizzers13",
  collegeTeam: "washington-b",
  playerName: "Falak Tulsi"
},
{
  id: 89,
  opponent: "SirPoetVic",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13145864",
  round: "Round 3",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: skizzers13",
  collegeTeam: "washington-b",
  playerName: "Falak Tulsi"
},
{
  id: 90,
  opponent: "sdpandit",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13253116",
  round: "Round 4",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: skizzers13",
  collegeTeam: "washington-b",
  playerName: "Falak Tulsi"
},
{
  id: 91,
  opponent: "sdpandit",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13253120",
  round: "Round 5",
  timeControl: "3+2",
  playedAs: "white",
  notes: "Player username: skizzers13",
  collegeTeam: "washington-b",
  playerName: "Falak Tulsi"
},
{
  id: 92,
  opponent: "sdpandit",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13253122",
  round: "Round 6",
  timeControl: "1+2",
  playedAs: "white",
  notes: "Player username: skizzers13",
  collegeTeam: "washington-b",
  playerName: "Falak Tulsi"
},
{
  id: 93,
  opponent: "sdpandit",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13253128",
  round: "Round 7",
  timeControl: "1+2",
  playedAs: "white",
  notes: "Player username: skizzers13",
  collegeTeam: "washington-b",
  playerName: "Falak Tulsi"
},
{
  id: 94,
  opponent: "sdpandit",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13253130",
  round: "Round 8",
  timeControl: "1+2",
  playedAs: "white",
  notes: "Player username: skizzers13",
  collegeTeam: "washington-b",
  playerName: "Falak Tulsi"
},
{
  id: 95,
  opponent: "sdpandit",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13253132",
  round: "Round 9",
  timeControl: "1+2",
  playedAs: "white",
  notes: "Player username: skizzers13",
  collegeTeam: "washington-b",
  playerName: "Falak Tulsi"
},
{
  id: 96,
  opponent: "sdpandit",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13253134",
  round: "Round 10",
  timeControl: "1+2",
  playedAs: "white",
  notes: "Player username: skizzers13",
  collegeTeam: "washington-b",
  playerName: "Falak Tulsi"
}, 
//kunal games 03/22
{
  id: 97,
  opponent: "Insaan0201",
  result: "win",
  date: "2025-03-22",
  chessComId: "13257208",
  round: "Round 1",
  timeControl: "5+2",
  playedAs: "black",
  notes: "Player username: king_kunal",
  collegeTeam: "vit-i",
  playerName: "Kunal Shrivastav"
},
{
  id: 98,
  opponent: "utkarsh0509",
  result: "win",
  date: "2025-03-22",
  chessComId: "13257214",
  round: "Round 2",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: king_kunal",
  collegeTeam: "vit-i",
  playerName: "Kunal Shrivastav"
},
{
  id: 99,
  opponent: "yashg_588",
  result: "win",
  date: "2025-03-22",
  chessComId: "13257218",
  round: "Round 3",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: king_kunal",
  collegeTeam: "vit-i",
  playerName: "Kunal Shrivastav"
},
{
  id: 100,
  opponent: "darkknight1231",
  result: "loss",
  date: "2025-03-22",
  chessComId: "13257220",
  round: "Round 4",
  timeControl: "5+2",
  playedAs: "black",
  notes: "Player username: king_kunal",
  collegeTeam: "vit-i",
  playerName: "Kunal Shrivastav"
},
{
  id: 101,
  opponent: "darkknight1231",
  result: "win",
  date: "2025-03-22",
  chessComId: "13257222",
  round: "Round 5",
  timeControl: "3+2",
  playedAs: "white",
  notes: "Player username: king_kunal",
  collegeTeam: "vit-i",
  playerName: "Kunal Shrivastav"
},
{
  id: 102,
  opponent: "darkknight1231",
  result: "win",
  date: "2025-03-22",
  chessComId: "13257224",
  round: "Round 6",
  timeControl: "1+2",
  playedAs: "black",
  notes: "Player username: king_kunal",
  collegeTeam: "vit-i",
  playerName: "Kunal Shrivastav"
},
//subermaanium chaacha 03/22
{
  id: 103,
  opponent: "utkarsh0509",
  result: "win",
  date: "2025-03-22",
  chessComId: "13257256",
  round: "Round 1",
  timeControl: "5+2",
  playedAs: "black",
  notes: "Player username: SuperMaanas",
  collegeTeam: "vit-i",
  playerName: "Maanas Kollegal"
},
{
  id: 104,
  opponent: "Insaan0201",
  result: "loss",
  date: "2025-03-22",
  chessComId: "13257262",
  round: "Round 2",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: SuperMaanas",
  collegeTeam: "vit-i",
  playerName: "Maanas Kollegal"
},
{
  id: 105,
  opponent: "darkknight1231",
  result: "loss",
  date: "2025-03-22",
  chessComId: "13257264",
  round: "Round 3",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: SuperMaanas",
  collegeTeam: "vit-i",
  playerName: "Maanas Kollegal"
},
{
  id: 106,
  opponent: "yashg_588",
  result: "win",
  date: "2025-03-22",
  chessComId: "13257268",
  round: "Round 4",
  timeControl: "5+2",
  playedAs: "black",
  notes: "Player username: SuperMaanas",
  collegeTeam: "vit-i",
  playerName: "Maanas Kollegal"
},
{
  id: 107,
  opponent: "yashg_588",
  result: "win",
  date: "2025-03-22",
  chessComId: "13257284",
  round: "Round 5",
  timeControl: "3+2",
  playedAs: "white",
  notes: "Player username: SuperMaanas",
  collegeTeam: "vit-i",
  playerName: "Maanas Kollegal"
},
{
  id: 108,
  opponent: "yashg_588",
  result: "win",
  date: "2025-03-22",
  chessComId: "13257288",
  round: "Round 6",
  timeControl: "1+2",
  playedAs: "black",
  notes: "Player username: SuperMaanas",
  collegeTeam: "vit-i",
  playerName: "Maanas Kollegal"
},
//vedh vasu games 03/22
{
  id: 109,
  opponent: "yashg_588",
  result: "loss",
  date: "2025-03-22",
  chessComId: "13257304",
  round: "Round 1",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: coolguy3949",
  collegeTeam: "vit-i",
  playerName: "Vedh Vasu"
},
{
  id: 110,
  opponent: "darkknight1231",
  result: "loss",
  date: "2025-03-22",
  chessComId: "13257306",
  round: "Round 2",
  timeControl: "5+2",
  playedAs: "black",
  notes: "Player username: coolguy3949",
  collegeTeam: "vit-i",
  playerName: "Vedh Vasu"
},
{
  id: 111,
  opponent: "Insaan0201",
  result: "loss",
  date: "2025-03-22",
  chessComId: "13257308",
  round: "Round 3",
  timeControl: "5+2",
  playedAs: "black",
  notes: "Player username: coolguy3949",
  collegeTeam: "vit-i",
  playerName: "Vedh Vasu"
},
{
  id: 112,
  opponent: "utkarsh0509",
  result: "win",
  date: "2025-03-22",
  chessComId: "13257310",
  round: "Round 4",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: coolguy3949",
  collegeTeam: "vit-i",
  playerName: "Vedh Vasu"
},
{
  id: 113,
  opponent: "utkarsh0509",
  result: "loss",
  date: "2025-03-22",
  chessComId: "13152114",
  round: "Round 5",
  timeControl: "3+2",
  playedAs: "black",
  notes: "Player username: coolguy3949",
  collegeTeam: "vit-i",
  playerName: "Vedh Vasu"
},
{
  id: 114,
  opponent: "utkarsh0509",
  result: "win",
  date: "2025-03-22",
  chessComId: "13152122",
  round: "Round 6",
  timeControl: "1+2",
  playedAs: "white",
  notes: "Player username: coolguy3949",
  collegeTeam: "vit-i",
  playerName: "Vedh Vasu"
},

//falak tulsi's games 03/22
{
  id: 115,
  opponent: "darkknight1231",
  result: "loss",
  date: "2025-03-22",
  chessComId: "13152132",
  round: "Round 1",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: skizzers13",
  collegeTeam: "vit-i",
  playerName: "Falak Tulsi"
},
{
  id: 116,
  opponent: "yashg_588",
  result: "loss",
  date: "2025-03-22",
  chessComId: "13152132",
  round: "Round 2",
  timeControl: "5+2",
  playedAs: "black",
  notes: "Player username: skizzers13",
  collegeTeam: "vit-i",
  playerName: "Falak Tulsi"
},
{
  id: 117,
  opponent: "yashg_588",
  result: "win",
  date: "2025-03-22",
  chessComId: "13152138",
  round: "Round 3",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: skizzers13",
  collegeTeam: "vit-i",
  playerName: "Falak Tulsi"
},
{
  id: 118,
  opponent: "Insaan0201",
  result: "win",
  date: "2025-03-22",
  chessComId: "13152144",
  round: "Round 4",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: skizzers13",
  collegeTeam: "vit-i",
  playerName: "Falak Tulsi"
},
{
  id: 119,
  opponent: "Insaan0201",
  result: "loss",
  date: "2025-03-22",
  chessComId: "13152150",
  round: "Round 5",
  timeControl: "3+2",
  playedAs: "black",
  notes: "Player username: skizzers13",
  collegeTeam: "vit-i",
  playerName: "Falak Tulsi"
},
{
  id: 120,
  opponent: "Insaan0201",
  result: "loss",
  date: "2025-03-22",
  chessComId: "13152152",
  round: "Round 6",
  timeControl: "1+2",
  playedAs: "white",
  notes: "Player username: skizzers13",
  collegeTeam: "vit-i",
  playerName: "Falak Tulsi"
}, 
//kunal playoffs 03/29
{
  id: 121,
  opponent: "jkmckenzzz",
  result: "win",
  date: "2025-03-29",
  chessComId: "13156230",
  round: "Round 1",
  timeControl: "5+2",
  playedAs: "black",
  notes: "Player username: king_kunal",
  collegeTeam: "univ-wash_playoff",
  playerName: "Kunal Shrivastav"
}, 
{
  id: 122,
  opponent: "kingofdapark",
  result: "win",
  date: "2025-03-29",
  chessComId: "13156236",
  round: "Round 2",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: king_kunal",
  collegeTeam: "univ-wash_playoff",
  playerName: "Kunal Shrivastav"
}, 
{
  id: 123,
  opponent: "SirPoetVic",
  result: "win",
  date: "2025-03-29",
  chessComId: "13156244",
  round: "Round 3",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: king_kunal",
  collegeTeam: "univ-wash_playoff",
  playerName: "Kunal Shrivastav"
}, 
{
  id: 124,
  opponent: "raigisan001",
  result: "win",
  date: "2025-03-29",
  chessComId: "13156254",
  round: "Round 4",
  timeControl: "5+2",
  playedAs: "black",
  notes: "Player username: king_kunal",
  collegeTeam: "univ-wash_playoff",
  playerName: "Kunal Shrivastav"
}, 
{
  id: 125,
  opponent: "raigisan001",
  result: "win",
  date: "2025-03-29",
  chessComId: "13156264",
  round: "Round 5",
  timeControl: "3+2",
  playedAs: "white",
  notes: "Player username: king_kunal",
  collegeTeam: "univ-wash_playoff",
  playerName: "Kunal Shrivastav"
}, 
//subermaanium chaacha playoffs
{
  id: 126,
  opponent: "kingofdapark",
  result: "win",
  date: "2025-03-29",
  chessComId: "13157396",
  round: "Round 1",
  timeControl: "5+2",
  playedAs: "black",
  notes: "Player username: SuperMaanas",
  collegeTeam: "univ-wash_playoff",
  playerName: "Maanas Kollegal"
}, 
{
  id: 127,
  opponent: "jkmckenzzz",
  result: "loss",
  date: "2025-03-29",
  chessComId: "13157402",
  round: "Round 2",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: SuperMaanas",
  collegeTeam: "univ-wash_playoff",
  playerName: "Maanas Kollegal"
}, 
{
  id: 128,
  opponent: "raigisan001",
  result: "loss",
  date: "2025-03-29",
  chessComId: "13157434",
  round: "Round 3",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: SuperMaanas",
  collegeTeam: "univ-wash_playoff",
  playerName: "Maanas Kollegal"
},
{
  id: 129,
  opponent: "SirPoetVic",
  result: "loss",
  date: "2025-03-29",
  chessComId: "13157438",
  round: "Round 4",
  timeControl: "5+2",
  playedAs: "black",
  notes: "Player username: SuperMaanas",
  collegeTeam: "univ-wash_playoff",
  playerName: "Maanas Kollegal"
}, 
{
  id: 130,
  opponent: "SirPoetVic",
  result: "win",
  date: "2025-03-29",
  chessComId: "13157444",
  round: "Round 5",
  timeControl: "3+2",
  playedAs: "white",
  notes: "Player username: SuperMaanas",
  collegeTeam: "univ-wash_playoff",
  playerName: "Maanas Kollegal"
},
//ved from the fed playoffs
{
  id: 131,
  opponent: "SirPoetVic",
  result: "loss",
  date: "2025-03-29",
  chessComId: "13157446",
  round: "Round 1",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: coolguy3949",
  collegeTeam: "univ-wash_playoff",
  playerName: "Vedh Vasu"
},
{
  id: 132,
  opponent: "raigisan001",
  result: "draw",
  date: "2025-03-29",
  chessComId: "13157452",
  round: "Round 2",
  timeControl: "5+2",
  playedAs: "black",
  notes: "Player username: coolguy3949",
  collegeTeam: "univ-wash_playoff",
  playerName: "Vedh Vasu"
}, 
{
  id: 133,
  opponent: "jkmckenzzz",
  result: "loss",
  date: "2025-03-29",
  chessComId: "13157458",
  round: "Round 3",
  timeControl: "5+2",
  playedAs: "black",
  notes: "Player username: coolguy3949",
  collegeTeam: "univ-wash_playoff",
  playerName: "Vedh Vasu"
}, 
{
  id: 134,
  opponent: "kingofdapark",
  result: "win",
  date: "2025-03-29",
  chessComId: "13157474",
  round: "Round 4",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: coolguy3949",
  collegeTeam: "univ-wash_playoff",
  playerName: "Vedh Vasu"
}, 
{
  id: 135,
  opponent: "kingofdapark",
  result: "loss",
  date: "2025-03-29",
  chessComId: "13157482",
  round: "Round 5",
  timeControl: "3+2",
  playedAs: "black",
  notes: "Player username: coolguy3949",
  collegeTeam: "univ-wash_playoff",
  playerName: "Vedh Vasu"
},


//Falak Tulsi playoffs
{
  id: 136,
  opponent: "raigisan001",
  result: "loss",
  date: "2025-03-29",
  chessComId: "13157500",
  round: "Round 1",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: skizzers13",
  collegeTeam: "univ-wash_playoff",
  playerName: "Falak Tulsi"
},

{
  id: 137,
  opponent: "SirPoetVic",
  result: "loss",
  date: "2025-03-29",
  chessComId: "13157526",
  round: "Round 2",
  timeControl: "5+2",
  playedAs: "black",
  notes: "Player username: skizzers13",
  collegeTeam: "univ-wash_playoff",
  playerName: "Falak Tulsi"
},
{
  id: 138,
  opponent: "kingofdapark",
  result: "win",
  date: "2025-03-29",
  chessComId: "13157528",
  round: "Round 3",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: skizzers13",
  collegeTeam: "univ-wash_playoff",
  playerName: "Falak Tulsi"
},
{
  id: 139,
  opponent: "jkmckenzzz",
  result: "draw",
  date: "2025-03-29",
  chessComId: "13157534",
  round: "Round 4",
  timeControl: "5+2",
  playedAs: "black",
  notes: "Player username: skizzers13",
  collegeTeam: "univ-wash_playoff",
  playerName: "Falak Tulsi"
},
{
  id: 140,
  opponent: "jkmckenzzz",
  result: "draw",
  date: "2025-03-29",
  chessComId: "13157542",
  round: "Round 5",
  timeControl: "3+2",
  playedAs: "white",
  notes: "Player username: skizzers13",
  collegeTeam: "univ-wash_playoff",
  playerName: "Falak Tulsi"

},


];