// gameData.ts
import { Game, CollegeTeam } from './types';

// College teams we played against
export const collegeTeams: CollegeTeam[] = [
  { name: "CCL UWATERLOO TEAM B W25", id: "uwaterloo-b" },
  { name: "University of Washington-B", id: "washington-b" },
  { name: "VIT I 2025 (INT CCL)", id: "vit-i" },
  { name: "University of Texas at Austin - D", id: "texas-austin-d" },
  { name: "UNIZAMBEZEA A", id: "unizambezea-a" },
];

// All games data
export const allGames: Game[] = [
  // Kunal vs UWATERLOO TEAM B
  { 
    id: 1, 
    opponent: "Chess_nut_Tree", 
    result: "win", 
    date: "2025-04-05",
    chessComId: "13139518",
    round: "Round 1",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: king_kunal",
    collegeTeam: "uwaterloo-b",
    playerName: "Kunal Shrivastav"
  },
  { 
    id: 2, 
    opponent: "Chyessirree", 
    result: "loss", 
    date: "2025-04-05",
    chessComId: "13139626",
    round: "Round 2",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: king_kunal",
    collegeTeam: "uwaterloo-b",
    playerName: "Kunal Shrivastav"
  },
  { 
    id: 3, 
    opponent: "lasdw", 
    result: "win", 
    date: "2025-04-05",
    chessComId: "13139646",
    round: "Round 3",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: king_kunal",
    collegeTeam: "uwaterloo-b",
    playerName: "Kunal Shrivastav"
  },
  { 
    id: 4, 
    opponent: "ComingForCM", 
    result: "win", 
    date: "2025-04-05",
    chessComId: "13139654",
    round: "Round 4",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: king_kunal",
    collegeTeam: "uwaterloo-b",
    playerName: "Kunal Shrivastav"
  },
  { 
    id: 5, 
    opponent: "ComingForCM", 
    result: "win", 
    date: "2025-04-05",
    chessComId: "13139656",
    round: "Round 5",
    timeControl: "3+2",
    playedAs: "black",
    notes: "Player username: king_kunal",
    collegeTeam: "uwaterloo-b",
    playerName: "Kunal Shrivastav"
  },
  { 
    id: 6, 
    opponent: "ComingForCM", 
    result: "win", 
    date: "2025-04-05",
    chessComId: "13139662",
    round: "Round 6 (Final)",
    timeControl: "1+2",
    playedAs: "white",
    notes: "Player username: king_kunal",
    collegeTeam: "uwaterloo-b",
    playerName: "Kunal Shrivastav"
  },
  
  // Kunal vs University of Texas at Austin - D
  {
    id: 7,
    opponent: "DieRoten4002",
    result: "win",
    date: "2025-03-01",
    chessComId: "13143978",
    round: "Round 1",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: king_kunal",
    collegeTeam: "texas-austin-d",
    playerName: "Kunal Shrivastav"
  },
  {
    id: 8,
    opponent: "ChessCraze012",
    result: "win",
    date: "2025-03-01",
    chessComId: "13143994",
    round: "Round 2",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: king_kunal",
    collegeTeam: "texas-austin-d",
    playerName: "Kunal Shrivastav"
  },
  {
    id: 9,
    opponent: "KnifeEffSix",
    result: "win",
    date: "2025-03-01",
    chessComId: "13144002",
    round: "Round 3",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: king_kunal",
    collegeTeam: "texas-austin-d",
    playerName: "Kunal Shrivastav"
  },
  {
    id: 10,
    opponent: "DrqgonRage",
    result: "win",
    date: "2025-03-01",
    chessComId: "13144004",
    round: "Round 4",
    timeControl: "5+2",
    playedAs: "black",
    collegeTeam: "texas-austin-d",
    playerName: "Kunal Shrivastav"
  },
  
  // Vedh vs UWATERLOO TEAM B
  {
    id: 11,
    opponent: "lasdw",
    result: "win",
    date: "2025-04-05",
    chessComId: "13139798",
    round: "Round 1",
    timeControl: "5+2",
    playedAs: "white",
    collegeTeam: "uwaterloo-b",
    playerName: "Vedh Vasu"
  },
  {
    id: 12,
    opponent: "ComingForCM",
    result: "loss",
    date: "2025-04-05",
    chessComId: "13139802",
    round: "Round 2",
    timeControl: "5+2",
    playedAs: "black",
    collegeTeam: "uwaterloo-b",
    playerName: "Vedh Vasu"
  },
  {
    id: 13,
    opponent: "Chess_nut_Tree",
    result: "win",
    date: "2025-04-05",
    chessComId: "13139810",
    round: "Round 3",
    timeControl: "5+2",
    playedAs: "white",
    collegeTeam: "uwaterloo-b",
    playerName: "Vedh Vasu"
  },
  {
    id: 14,
    opponent: "Chyessirree",
    result: "win",
    date: "2025-04-05",
    chessComId: "13139814",
    round: "Round 4",
    timeControl: "5+2",
    playedAs: "black",
    collegeTeam: "uwaterloo-b",
    playerName: "Vedh Vasu"
  },
  {
    id: 15,
    opponent: "Chyessirree",
    result: "loss",
    date: "2025-04-05",
    chessComId: "13139828",
    round: "Round 5",
    timeControl: "3+2",
    playedAs: "white",
    collegeTeam: "uwaterloo-b",
    playerName: "Vedh Vasu"
  },
  {
    id: 16,
    opponent: "Chyessirree",
    result: "win",
    date: "2025-04-05",
    chessComId: "13139830",
    round: "Round 6 (Final)",
    timeControl: "1+2",
    playedAs: "black",
    collegeTeam: "uwaterloo-b",
    playerName: "Vedh Vasu"
  },
  
  // Vedh vs University of Texas at Austin - D
  {
    id: 17,
    opponent: "KnifeEffSix",
    result: "loss",
    date: "2025-03-01",
    chessComId: "13144104",
    round: "Round 1",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: coolguy3949",
    collegeTeam: "texas-austin-d",
    playerName: "Vedh Vasu"
  },
  {
    id: 18,
    opponent: "DrqgonRage",
    result: "loss",
    date: "2025-03-01",
    chessComId: "13144108",
    round: "Round 2",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: coolguy3949",
    collegeTeam: "texas-austin-d",
    playerName: "Vedh Vasu"
  },
  {
    id: 19,
    opponent: "DieRoten4002",
    result: "loss",
    date: "2025-03-01",
    chessComId: "13144110",
    round: "Round 3",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: coolguy3949",
    collegeTeam: "texas-austin-d",
    playerName: "Vedh Vasu"
  },
  {
    id: 20,
    opponent: "ChessCraze012",
    result: "win",
    date: "2025-03-01",
    chessComId: "13144118",
    round: "Round 4",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: coolguy3949",
    collegeTeam: "texas-austin-d",
    playerName: "Vedh Vasu"
  },
  
  // Falak vs UWATERLOO TEAM B
  {
    id: 21,
    opponent: "ComingForCM",
    result: "loss",
    date: "2025-04-05",
    chessComId: "13139882",
    round: "Round 1",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: skizzers13",
    collegeTeam: "uwaterloo-b",
    playerName: "Falak Tulsi"
  },
  {
    id: 22,
    opponent: "lasdw",
    result: "loss",
    date: "2025-04-05",
    chessComId: "13139884",
    round: "Round 2",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: skizzers13",
    collegeTeam: "uwaterloo-b",
    playerName: "Falak Tulsi"
  },
  {
    id: 23,
    opponent: "N/A",
    result: "loss",
    date: "2025-04-05",
    round: "Round 3",
    timeControl: "N/A",
    notes: "Player did not participate",
    collegeTeam: "uwaterloo-b",
    playerName: "Falak Tulsi"
  },
  {
    id: 24,
    opponent: "N/A",
    result: "loss",
    date: "2025-04-05",
    round: "Round 4",
    timeControl: "N/A",
    notes: "Player did not participate",
    collegeTeam: "uwaterloo-b",
    playerName: "Falak Tulsi"
  },
  {
    id: 25,
    opponent: "N/A",
    result: "loss",
    date: "2025-04-05",
    round: "Round 5",
    timeControl: "N/A",
    notes: "Player did not participate",
    collegeTeam: "uwaterloo-b",
    playerName: "Falak Tulsi"
  },
  {
    id: 26,
    opponent: "N/A",
    result: "loss",
    date: "2025-04-05",
    round: "Round 6",
    timeControl: "N/A",
    notes: "Player did not participate",
    collegeTeam: "uwaterloo-b",
    playerName: "Falak Tulsi"
  },
  
  // Maanas vs UWATERLOO TEAM B
  {
    id: 27,
    opponent: "Chyessirree",
    result: "win",
    date: "2025-04-05",
    chessComId: "13140094",
    round: "Round 1",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: SuperMaanas",
    collegeTeam: "uwaterloo-b",
    playerName: "Maanas Kollegal"
  },
  {
    id: 28,
    opponent: "Chess_nut_Tree",
    result: "win",
    date: "2025-04-05",
    chessComId: "13140132",
    round: "Round 2",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: SuperMaanas",
    collegeTeam: "uwaterloo-b",
    playerName: "Maanas Kollegal"
  },
  {
    id: 29,
    opponent: "ComingForCM",
    result: "loss",
    date: "2025-04-05",
    chessComId: "13140136",
    round: "Round 3",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: SuperMaanas",
    collegeTeam: "uwaterloo-b",
    playerName: "Maanas Kollegal"
  },
  {
    id: 30,
    opponent: "lasdw",
    result: "loss",
    date: "2025-04-05",
    chessComId: "13140148",
    round: "Round 4",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: SuperMaanas",
    collegeTeam: "uwaterloo-b",
    playerName: "Maanas Kollegal"
  },
  {
    id: 31,
    opponent: "lasdw",
    result: "win",
    date: "2025-04-05",
    chessComId: "13140152",
    round: "Round 5",
    timeControl: "3+2",
    playedAs: "black",
    notes: "Player username: SuperMaanas",
    collegeTeam: "uwaterloo-b",
    playerName: "Maanas Kollegal"
  },
  {
    id: 32,
    opponent: "lasdw",
    result: "win",
    date: "2025-04-05",
    chessComId: "13140156",
    round: "Round 6 (Final)",
    timeControl: "1+2",
    playedAs: "white",
    notes: "Player username: SuperMaanas",
    collegeTeam: "uwaterloo-b",
    playerName: "Maanas Kollegal"
  },
  // Maanas vs University of Texas at Austin - D
  {
    id: 33,
    opponent: "ChessCraze012",
    result: "draw",
    date: "2025-03-01",
    chessComId: "13144500",
    round: "Round 1",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: SuperMaanas",
    collegeTeam: "texas-austin-d",
    playerName: "Maanas Kollegal"
  },
  {
    id: 34,
    opponent: "DieRoten4002",
    result: "win",
    date: "2025-03-01",
    chessComId: "13144502",
    round: "Round 2",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: SuperMaanas",
    collegeTeam: "texas-austin-d",
    playerName: "Maanas Kollegal"
  },
  {
    id: 35,
    opponent: "DrqgonRage",
    result: "win",
    date: "2025-03-01",
    chessComId: "13144504",
    round: "Round 3",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: SuperMaanas",
    collegeTeam: "texas-austin-d",
    playerName: "Maanas Kollegal"
  },
  {
    id: 36,
    opponent: "KnifeEffSix",
    result: "draw",
    date: "2025-03-01",
    chessComId: "13144506",
    round: "Round 4",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: SuperMaanas",
    collegeTeam: "texas-austin-d",
    playerName: "Maanas Kollegal"
  },
  // Falak vs University of Texas at Austin - D
  {
    id: 37,
    opponent: "DrqgonRage",
    result: "win",
    date: "2025-03-01",
    chessComId: "13144544",
    round: "Round 1",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: skizzers13",
    collegeTeam: "texas-austin-d",
    playerName: "Falak Tulsi"
  },
  {
    id: 38,
    opponent: "KnifeEffSix",
    result: "loss",
    date: "2025-03-01",
    chessComId: "13144546",
    round: "Round 2",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: skizzers13",
    collegeTeam: "texas-austin-d",
    playerName: "Falak Tulsi"
  },
  {
    id: 39,
    opponent: "ChessCraze012",
    result: "loss",
    date: "2025-03-01",
    chessComId: "13144552",
    round: "Round 3",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: skizzers13",
    collegeTeam: "texas-austin-d",
    playerName: "Falak Tulsi"
  },
  {
    id: 40,
    opponent: "DieRoten4002",
    result: "loss",
    date: "2025-03-01",
    chessComId: "13144556",
    round: "Round 4",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: skizzers13",
    collegeTeam: "texas-austin-d",
    playerName: "Falak Tulsi"
  },
  // Kunal vs UNIZAMBEZEA A
  {
    id: 41,
    opponent: "Elio_3",
    result: "win",
    date: "2025-02-08",
    chessComId: "13144726",
    round: "Round 1",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: king_kunal",
    collegeTeam: "unizambezea-a",
    playerName: "Kunal Shrivastav"
  },
  {
    id: 42,
    opponent: "Chissale19QI",
    result: "win",
    date: "2025-02-08",
    chessComId: "13144736",
    round: "Round 2",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: king_kunal",
    collegeTeam: "unizambezea-a",
    playerName: "Kunal Shrivastav"
  },
  {
    id: 43,
    opponent: "agm2002",
    result: "win",
    date: "2025-02-08",
    chessComId: "13144744",
    round: "Round 3",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: king_kunal",
    collegeTeam: "unizambezea-a",
    playerName: "Kunal Shrivastav"
  },
  {
    id: 44,
    opponent: "jojoabdul",
    result: "win",
    date: "2025-02-08",
    chessComId: "13144746",
    round: "Round 4",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: king_kunal",
    collegeTeam: "unizambezea-a",
    playerName: "Kunal Shrivastav"
  },
  // Maanas vs UNIZAMBEZEA A
  {
    id: 45,
    opponent: "Chissale19QI",
    result: "win",
    date: "2025-02-08",
    chessComId: "13144760",
    round: "Round 1",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: SuperMaanas",
    collegeTeam: "unizambezea-a",
    playerName: "Maanas Kollegal"
  },
  {
    id: 46,
    opponent: "Elio_3",
    result: "win",
    date: "2025-02-08",
    chessComId: "13144764",
    round: "Round 2",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: SuperMaanas",
    collegeTeam: "unizambezea-a",
    playerName: "Maanas Kollegal"
  },
  {
    id: 47,
    opponent: "jojoabdul",
    result: "loss",
    date: "2025-02-08",
    chessComId: "13144766",
    round: "Round 3",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: SuperMaanas",
    collegeTeam: "unizambezea-a",
    playerName: "Maanas Kollegal"
  },
  {
    id: 48,
    opponent: "agm2002",
    result: "loss",
    date: "2025-02-08",
    chessComId: "13144768",
    round: "Round 4",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: SuperMaanas",
    collegeTeam: "unizambezea-a",
    playerName: "Maanas Kollegal"
  },
  {
    id: 49,
    opponent: "agm2002",
    result: "loss",
    date: "2025-02-08",
    chessComId: "13144784",
    round: "Round 1",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: coolguy3949",
    collegeTeam: "unizambezea-a",
    playerName: "Vedh Vasu"
  },
  {
    id: 50,
    opponent: "jojoabdul",
    result: "loss",
    date: "2025-02-08",
    chessComId: "13144792",
    round: "Round 2",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: coolguy3949",
    collegeTeam: "unizambezea-a",
    playerName: "Vedh Vasu"
  },
  {
    id: 51,
    opponent: "Elio_3",
    result: "win",
    date: "2025-02-08",
    chessComId: "13144802",
    round: "Round 3",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: coolguy3949",
    collegeTeam: "unizambezea-a",
    playerName: "Vedh Vasu"
  },
  {
    id: 52,
    opponent: "Chissale19QI",
    result: "draw",
    date: "2025-02-08",
    chessComId: "13144814",
    round: "Round 4",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: coolguy3949",
    collegeTeam: "unizambezea-a",
    playerName: "Vedh Vasu"
  },
  {
    id: 53,
    opponent: "jojoabdul",
    result: "loss",
    date: "2025-02-08",
    chessComId: "13144866",
    round: "Round 1",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: skizzers13",
    collegeTeam: "unizambezea-a",
    playerName: "Falak Tulsi"
  },
  {
    id: 54,
    opponent: "agm2002",
    result: "win",
    date: "2025-02-08",
    chessComId: "13144876",
    round: "Round 2",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: skizzers13",
    collegeTeam: "unizambezea-a",
    playerName: "Falak Tulsi"
  },
  {
    id: 55,
    opponent: "Chissale19QI",
    result: "loss",
    date: "2025-02-08",
    chessComId: "13144888",
    round: "Round 3",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: skizzers13",
    collegeTeam: "unizambezea-a",
    playerName: "Falak Tulsi"
  },
  {
    id: 56,
    opponent: "Elio_3",
    result: "win",
    date: "2025-02-08",
    chessComId: "13144890",
    round: "Round 4",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: skizzers13",
    collegeTeam: "unizambezea-a",
    playerName: "Falak Tulsi"
  },
  //kunal games against univ-washington 03/08/
  {
    id: 57,
    opponent: "sdpandit",
    result: "win",
    date: "2025-03-08",
    chessComId: "13145594",
    round: "Round 1",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: king_kunal",
    collegeTeam: "washington-b",
    playerName: "Kunal Shrivastav"
  },
  {
    id: 58,
    opponent: "SirPoetVic",
    result: "win",
    date: "2025-03-08",
    chessComId: "13145604",
    round: "Round 2",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: king_kunal",
    collegeTeam: "washington-b",
    playerName: "Kunal Shrivastav"
  },
  {
    id: 59,
    opponent: "LionBlade45",
    result: "win",
    date: "2025-03-08",
    chessComId: "13145610",
    round: "Round 3",
    timeControl: "5+2",
    playedAs: "black",
    notes: "Player username: king_kunal",
    collegeTeam: "washington-b",
    playerName: "Kunal Shrivastav"
  },
  {
    id: 60,
    opponent: "jkmckenzzz",
    result: "win",
    date: "2025-03-08",
    chessComId: "13145620",
    round: "Round 4",
    timeControl: "5+2",
    playedAs: "white",
    notes: "Player username: king_kunal",
    collegeTeam: "washington-b",
    playerName: "Kunal Shrivastav"
  }, 
  {
    id: 61,
    opponent: "jkmckenzzz",
    result: "win",
    date: "2025-03-08",
    chessComId: "13145638",
    round: "Round 5",
    timeControl: "3+2",
    playedAs: "black",
    notes: "Player username: king_kunal",
    collegeTeam: "washington-b",
    playerName: "Kunal Shrivastav"
  }, 
  {
    id: 62,
    opponent: "jkmckenzzz",
    result: "win",
    date: "2025-03-08",
    chessComId: "13145640",
    round: "Round 6",
    timeControl: "1+2",
    playedAs: "white",
    notes: "Player username: king_kunal",
    collegeTeam: "washington-b",
    playerName: "Kunal Shrivastav"
  }, 
  {
    id: 63,
    opponent: "jkmckenzzz",
    result: "win",
    date: "2025-03-08",
    chessComId: "13145644",
    round: "Round 7",
    timeControl: "1+2",
    playedAs: "black",
    notes: "Player username: king_kunal",
    collegeTeam: "washington-b",
    playerName: "Kunal Shrivastav"
  }, 
  {
    id: 64,
    opponent: "jkmckenzzz",
    result: "win",
    date: "2025-03-08",
    chessComId: "13145650",
    round: "Round 8",
    timeControl: "1+2",
    playedAs: "white",
    notes: "Player username: king_kunal",
    collegeTeam: "washington-b",
    playerName: "Kunal Shrivastav"
  }, 
  {
    id: 65,
    opponent: "jkmckenzzz",
    result: "win",
    date: "2025-03-08",
    chessComId: "13145652",
    round: "Round 9",
    timeControl: "1+2",
    playedAs: "black",
    notes: "Player username: king_kunal",
    collegeTeam: "washington-b",
    playerName: "Kunal Shrivastav"
  }, 
  {
    id: 66,
    opponent: "jkmckenzzz",
    result: "win",
    date: "2025-03-08",
    chessComId: "13145654",
    round: "Round 10",
    timeControl: "1+2",
    playedAs: "white",
    notes: "Player username: king_kunal",
    collegeTeam: "washington-b",
    playerName: "Kunal Shrivastav"
  }, 

  //maanas games against Univ. Washington
  {
    id: 67,
    opponent: "SirPoetVic",
    result: "draw",
    date: "2025-03-08",
    chessComId: "13145680",
    round: "Round 1",
    timeControl: "5+2",
    playedAs: "black",
    collegeTeam: "washington-b",
    playerName: "Maanas Kollegal"
  },
  {
    id: 68,
    opponent: "sdpandit",
    result: "win",
    date: "2025-03-08",
    chessComId: "13145686",
    round: "Round 2",
    timeControl: "5+2",
    playedAs: "white",
    collegeTeam: "washington-b",
    playerName: "Maanas Kollegal"
  },
  {
    id: 69,
    opponent: "jkmckenzzz",
    result: "win",
    date: "2025-03-08",
    chessComId: "13145610",
    round: "Round 3",
    timeControl: "5+2",
    playedAs: "black",
    collegeTeam: "washington-b",
    playerName: "Maanas Kollegal"
  },
  {
    id: 70,
    opponent: "LionBlade45",
    result: "win",
    date: "2025-03-08",
    chessComId: "13145692",
    round: "Round 4",
    timeControl: "5+2",
    playedAs: "white",
    collegeTeam: "washington-b",
    playerName: "Maanas Kollegal"
  }, 
  {
    id: 71,
    opponent: "LionBlade45",
    result: "win",
    date: "2025-03-08",
    chessComId: "13145696",
    round: "Round 5",
    timeControl: "3+2",
    playedAs: "white",
    collegeTeam: "washington-b",
    playerName: "Maanas Kollegal"
  }, 
  {
    id: 72,
    opponent: "LionBlade45",
    result: "win",
    date: "2025-03-08",
    chessComId: "13145702",
    round: "Round 6",
    timeControl: "1+2",
    playedAs: "black",
    collegeTeam: "washington-b",
    playerName: "Maanas Kollegal"
  }, 
  {
    id: 73,
    opponent: "LionBlade45",
    result: "win",
    date: "2025-03-08",
    chessComId: "13145712",
    round: "Round 7",
    timeControl: "1+2",
    playedAs: "white",
    collegeTeam: "washington-b",
    playerName: "Maanas Kollegal"
  }, 
  {
    id: 74,
    opponent: "LionBlade45",
    result: "win",
    date: "2025-03-08",
    chessComId: "13145714",
    round: "Round 8",
    timeControl: "1+2",
    playedAs: "black",
    collegeTeam: "washington-b",
    playerName: "Maanas Kollegal"
  }, 
  {
    id: 75,
    opponent: "LionBlade45",
    result: "loss",
    date: "2025-03-08",
    chessComId: "13145718",
    round: "Round 9",
    timeControl: "1+2",
    playedAs: "white",
    collegeTeam: "washington-b",
    playerName: "Maanas Kollegal"
  }, 
  {
    id: 76,
    opponent: "LionBlade45",
    result: "win",
    date: "2025-03-08",
    chessComId: "13145724",
    round: "Round 10",
    timeControl: "1+2",
    playedAs: "black",
    collegeTeam: "washington-b",
    playerName: "Maanas Kollegal"
  },

  //vedh vasu's games against Univ-Washington 03/08
{
  id: 77,
  opponent: "LionBlade45",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13145740",
  round: "Round 1",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: coolguy3949",
  collegeTeam: "washington-b",
  playerName: "Vedh Vasu"
},
{
  id: 78,
  opponent: "jkmckenzzz",
  result: "draw",
  date: "2025-03-08",
  chessComId: "13145742",
  round: "Round 2",
  timeControl: "5+2",
  playedAs: "black",
  notes: "Player username: coolguy3949",
  collegeTeam: "washington-b",
  playerName: "Vedh Vasu"
},
{
  id: 79,
  opponent: "sdpandit",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13145744",
  round: "Round 3",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: coolguy3949",
  collegeTeam: "washington-b",
  playerName: "Vedh Vasu"
},
{
  id: 80,
  opponent: "SirPoetVic",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13145748",
  round: "Round 4",
  timeControl: "5+2",
  playedAs: "black",
  notes: "Player username: coolguy3949",
  collegeTeam: "washington-b",
  playerName: "Vedh Vasu"
},
{
  id: 81,
  opponent: "SirPoetVic",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13145752",
  round: "Round 5",
  timeControl: "3+2",
  playedAs: "white",
  notes: "Player username: coolguy3949",
  collegeTeam: "washington-b",
  playerName: "Vedh Vasu"
},
{
  id: 82,
  opponent: "SirPoetVic",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13145756",
  round: "Round 6",
  timeControl: "1+2",
  playedAs: "black",
  notes: "Player username: coolguy3949",
  collegeTeam: "washington-b",
  playerName: "Vedh Vasu"
},
{
  id: 83,
  opponent: "SirPoetVic",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13145758",
  round: "Round 7",
  timeControl: "1+2",
  playedAs: "white",
  notes: "Player username: coolguy3949",
  collegeTeam: "washington-b",
  playerName: "Vedh Vasu"
},
{
  id: 84,
  opponent: "SirPoetVic",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13145776",
  round: "Round 8",
  timeControl: "1+2",
  playedAs: "black",
  notes: "Player username: coolguy3949",
  collegeTeam: "washington-b",
  playerName: "Vedh Vasu"
},
{
  id: 85,
  opponent: "SirPoetVic",
  result: "win",
  date: "2025-03-08",
  chessComId: "13145778",
  round: "Round 9",
  timeControl: "1+2",
  playedAs: "white",
  notes: "Player username: coolguy3949",
  collegeTeam: "washington-b",
  playerName: "Vedh Vasu"
},
{
  id: 86,
  opponent: "SirPoetVic",
  result: "win",
  date: "2025-03-08",
  chessComId: "13145784",
  round: "Round 10",
  timeControl: "1+2",
  playedAs: "black",
  notes: "Player username: coolguy3949",
  collegeTeam: "washington-b",
  playerName: "Vedh Vasu"
},

//Falak Tulsi's games against Univ-Washington 03/08
{
  id: 87,
  opponent: "jkmckenzzz",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13145812",
  round: "Round 1",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: skizzers13",
  collegeTeam: "washington-b",
  playerName: "Falak Tulsi"
},
{
  id: 88,
  opponent: "LionBlade45",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13145828",
  round: "Round 2",
  timeControl: "5+2",
  playedAs: "black",
  notes: "Player username: skizzers13",
  collegeTeam: "washington-b",
  playerName: "Falak Tulsi"
},
{
  id: 89,
  opponent: "SirPoetVic",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13145864",
  round: "Round 3",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: skizzers13",
  collegeTeam: "washington-b",
  playerName: "Falak Tulsi"
},
{
  id: 90,
  opponent: "sdpandit",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13145868",
  round: "Round 4",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: skizzers13",
  collegeTeam: "washington-b",
  playerName: "Falak Tulsi"
},
{
  id: 91,
  opponent: "sdpandit",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13145870",
  round: "Round 5",
  timeControl: "3+2",
  playedAs: "white",
  notes: "Player username: skizzers13",
  collegeTeam: "washington-b",
  playerName: "Falak Tulsi"
},
{
  id: 92,
  opponent: "sdpandit",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13145872",
  round: "Round 6",
  timeControl: "1+2",
  playedAs: "white",
  notes: "Player username: skizzers13",
  collegeTeam: "washington-b",
  playerName: "Falak Tulsi"
},
{
  id: 93,
  opponent: "sdpandit",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13145874",
  round: "Round 7",
  timeControl: "1+2",
  playedAs: "white",
  notes: "Player username: skizzers13",
  collegeTeam: "washington-b",
  playerName: "Falak Tulsi"
},
{
  id: 94,
  opponent: "sdpandit",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13145876",
  round: "Round 8",
  timeControl: "1+2",
  playedAs: "white",
  notes: "Player username: skizzers13",
  collegeTeam: "washington-b",
  playerName: "Falak Tulsi"
},
{
  id: 95,
  opponent: "sdpandit",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13145878",
  round: "Round 9",
  timeControl: "1+2",
  playedAs: "white",
  notes: "Player username: skizzers13",
  collegeTeam: "washington-b",
  playerName: "Falak Tulsi"
},
{
  id: 96,
  opponent: "sdpandit",
  result: "loss",
  date: "2025-03-08",
  chessComId: "13145880",
  round: "Round 10",
  timeControl: "1+2",
  playedAs: "white",
  notes: "Player username: skizzers13",
  collegeTeam: "washington-b",
  playerName: "Falak Tulsi"
}, 
//kunal games 03/22
{
  id: 97,
  opponent: "Insaan0201",
  result: "win",
  date: "2025-03-22",
  chessComId: "13152000",
  round: "Round 1",
  timeControl: "5+2",
  playedAs: "black",
  notes: "Player username: king_kunal",
  collegeTeam: "vit-i",
  playerName: "Kunal Shrivastav"
},
{
  id: 98,
  opponent: "utkarsh0509",
  result: "win",
  date: "2025-03-22",
  chessComId: "13152020",
  round: "Round 2",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: king_kunal",
  collegeTeam: "vit-i",
  playerName: "Kunal Shrivastav"
},
{
  id: 99,
  opponent: "yashg_588",
  result: "win",
  date: "2025-03-22",
  chessComId: "13152026",
  round: "Round 3",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: king_kunal",
  collegeTeam: "vit-i",
  playerName: "Kunal Shrivastav"
},
{
  id: 100,
  opponent: "darkknight1231",
  result: "loss",
  date: "2025-03-22",
  chessComId: "13152034",
  round: "Round 4",
  timeControl: "5+2",
  playedAs: "black",
  notes: "Player username: king_kunal",
  collegeTeam: "vit-i",
  playerName: "Kunal Shrivastav"
},
{
  id: 101,
  opponent: "darkknight1231",
  result: "win",
  date: "2025-03-22",
  chessComId: "13152042",
  round: "Round 5",
  timeControl: "3+2",
  playedAs: "white",
  notes: "Player username: king_kunal",
  collegeTeam: "vit-i",
  playerName: "Kunal Shrivastav"
},
{
  id: 102,
  opponent: "darkknight1231",
  result: "win",
  date: "2025-03-22",
  chessComId: "13152052",
  round: "Round 6",
  timeControl: "1+2",
  playedAs: "black",
  notes: "Player username: king_kunal",
  collegeTeam: "vit-i",
  playerName: "Kunal Shrivastav"
},
//subermaanium chaacha 03/22
{
  id: 103,
  opponent: "utkarsh0509",
  result: "win",
  date: "2025-03-22",
  chessComId: "13152060",
  round: "Round 1",
  timeControl: "5+2",
  playedAs: "black",
  notes: "Player username: SuperMaanas",
  collegeTeam: "vit-i",
  playerName: "Maanas Kollegal"
},
{
  id: 104,
  opponent: "Insaan0201",
  result: "loss",
  date: "2025-03-22",
  chessComId: "13152078",
  round: "Round 2",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: SuperMaanas",
  collegeTeam: "vit-i",
  playerName: "Maanas Kollegal"
},
{
  id: 105,
  opponent: "darkknight1231",
  result: "loss",
  date: "2025-03-22",
  chessComId: "13152084",
  round: "Round 3",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: SuperMaanas",
  collegeTeam: "vit-i",
  playerName: "Maanas Kollegal"
},
{
  id: 106,
  opponent: "yashg_588",
  result: "win",
  date: "2025-03-22",
  chessComId: "13152060",
  round: "Round 4",
  timeControl: "5+2",
  playedAs: "black",
  notes: "Player username: SuperMaanas",
  collegeTeam: "vit-i",
  playerName: "Maanas Kollegal"
},
{
  id: 107,
  opponent: "yashg_588",
  result: "win",
  date: "2025-03-22",
  chessComId: "13152092",
  round: "Round 5",
  timeControl: "3+2",
  playedAs: "white",
  notes: "Player username: SuperMaanas",
  collegeTeam: "vit-i",
  playerName: "Maanas Kollegal"
},
{
  id: 108,
  opponent: "yashg_588",
  result: "win",
  date: "2025-03-22",
  chessComId: "13152094",
  round: "Round 6",
  timeControl: "1+2",
  playedAs: "black",
  notes: "Player username: SuperMaanas",
  collegeTeam: "vit-i",
  playerName: "Maanas Kollegal"
},
//vedh vasu games 03/22
{
  id: 109,
  opponent: "yashg_588",
  result: "loss",
  date: "2025-03-22",
  chessComId: "13152096",
  round: "Round 1",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: coolguy3949",
  collegeTeam: "vit-i",
  playerName: "Vedh Vasu"
},
{
  id: 110,
  opponent: "darkknight1231",
  result: "loss",
  date: "2025-03-22",
  chessComId: "13152102",
  round: "Round 2",
  timeControl: "5+2",
  playedAs: "black",
  notes: "Player username: coolguy3949",
  collegeTeam: "vit-i",
  playerName: "Vedh Vasu"
},
{
  id: 111,
  opponent: "Insaan0201",
  result: "loss",
  date: "2025-03-22",
  chessComId: "13152104",
  round: "Round 3",
  timeControl: "5+2",
  playedAs: "black",
  notes: "Player username: coolguy3949",
  collegeTeam: "vit-i",
  playerName: "Vedh Vasu"
},
{
  id: 112,
  opponent: "utkarsh0509",
  result: "win",
  date: "2025-03-22",
  chessComId: "13152110",
  round: "Round 4",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: coolguy3949",
  collegeTeam: "vit-i",
  playerName: "Vedh Vasu"
},
{
  id: 113,
  opponent: "utkarsh0509",
  result: "loss",
  date: "2025-03-22",
  chessComId: "13152114",
  round: "Round 5",
  timeControl: "3+2",
  playedAs: "black",
  notes: "Player username: coolguy3949",
  collegeTeam: "vit-i",
  playerName: "Vedh Vasu"
},
{
  id: 114,
  opponent: "utkarsh0509",
  result: "win",
  date: "2025-03-22",
  chessComId: "13152122",
  round: "Round 6",
  timeControl: "1+2",
  playedAs: "white",
  notes: "Player username: coolguy3949",
  collegeTeam: "vit-i",
  playerName: "Vedh Vasu"
},

//falak tulsi's games 03/22
{
  id: 115,
  opponent: "darkknight1231",
  result: "loss",
  date: "2025-03-22",
  chessComId: "13152132",
  round: "Round 1",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: skizzers13",
  collegeTeam: "vit-i",
  playerName: "Falak Tulsi"
},
{
  id: 116,
  opponent: "yashg_588",
  result: "loss",
  date: "2025-03-22",
  chessComId: "13152132",
  round: "Round 2",
  timeControl: "5+2",
  playedAs: "black",
  notes: "Player username: skizzers13",
  collegeTeam: "vit-i",
  playerName: "Falak Tulsi"
},
{
  id: 117,
  opponent: "yashg_588",
  result: "win",
  date: "2025-03-22",
  chessComId: "13152138",
  round: "Round 3",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: skizzers13",
  collegeTeam: "vit-i",
  playerName: "Falak Tulsi"
},
{
  id: 118,
  opponent: "Insaan0201",
  result: "win",
  date: "2025-03-22",
  chessComId: "13152144",
  round: "Round 4",
  timeControl: "5+2",
  playedAs: "white",
  notes: "Player username: skizzers13",
  collegeTeam: "vit-i",
  playerName: "Falak Tulsi"
},
{
  id: 119,
  opponent: "Insaan0201",
  result: "loss",
  date: "2025-03-22",
  chessComId: "13152150",
  round: "Round 5",
  timeControl: "3+2",
  playedAs: "black",
  notes: "Player username: skizzers13",
  collegeTeam: "vit-i",
  playerName: "Falak Tulsi"
},
{
  id: 120,
  opponent: "Insaan0201",
  result: "loss",
  date: "2025-03-22",
  chessComId: "13152152",
  round: "Round 6",
  timeControl: "1+2",
  playedAs: "white",
  notes: "Player username: skizzers13",
  collegeTeam: "vit-i",
  playerName: "Falak Tulsi"
}, 
];